{% set name = "vl-convert" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vega/vl-convert/archive/refs/tags/vl-convert@{{ version }}.tar.gz
  sha256: 19a33b8ac20fd1a071a8a5d9b0afcc9e53c2aef21652a07614355352bed47a1d

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - cmake
    - rust >=1.64.0
    - protobuf
  run:
   - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.13") }}  # [osx and x86_64]

test:
  commands:
    - vl-convert --help

about:
  home: https://github.com/vega/vl-convert
  license: BSD-3-Clause
  license_family: BSD
  license_file: 
      - vl-convert/LICENSE
      - vl-convert/thirdparty_font.md
      - vl-convert/thirdparty_javascript.md
      - vl-convert/thirdparty_rust.yaml
  summary: A tool for converting Vega-Lite chart specifications into static images (SVG or PNG) or Vega chart specifications.
  description: |
    A tool for converting Vega-Lite chart specifications into static images (SVG or PNG) or Vega chart specifications.
  doc_url: https://github.com/vega/vl-convert
  dev_url: https://github.com/vega/vl-convert

extra:
  recipe-maintainers:
    - felixmoelder
